BlogApp/Models/HomeBlogModel.cs
using BlogApp.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.Models
{
    public class HomeBlogModel
    {
        public List<Blog> SliderBlogs { get; set; }
        public List<Blog> HomeBlogs { get; set; }

    }
}

BlogApp/Controllers/BlogController.cs
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository _blogRepository;
        private ICategoryRepository _categoryRepository;
        public BlogController(IBlogRepository _blogRepo, ICategoryRepository _categoryRepo)
        {
            _blogRepository = _blogRepo;
            _categoryRepository = _categoryRepo;
        }
        public IActionResult Index(int? id, string q)
        {
            var query = _blogRepository.GetAll().Where(i => i.isApproved);

            if (id != null)
            {
                query = query.Where(i => i.CategoryId == id).OrderByDescending(i => i.Date);


            }
            if (!string.IsNullOrEmpty(q))
            {
                //query = query.Where(i => i.Title.Contains(q) || i.Description.Contains(q) || i.Body.Contains(q));
                query = query.Where(i => EF.Functions.Like(i.Title, "%"+q+"%") || EF.Functions.Like(i.Description, "%" + q + "%") || EF.Functions.Like(i.Body, "%" + q + "%"));

            }
            return View(query);
        }
        public IActionResult List()
        {
            return View(_blogRepository.GetAll()); 
        }
       
        
        //[HttpGet]
        //public IActionResult AddOrUpdate(int? id)
        //{
        //    ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");

        //    if (id==null)
        //    {

        //        return View(new Blog());
        //    }
        //    else
        //    {
        //        return View(_blogRepository.GetById((int)id));
        //    }
        //}

        //[HttpPost]
        //public IActionResult AddOrUpdate(Blog entity)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _blogRepository.SaveBlog(entity);
        //        TempData["message"] = $"{entity.Title} kayit edildi";
        //        return RedirectToAction("List");
        //    }
        //    ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");

        //    return View(entity);
        //}

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_blogRepository.GetById(id));
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int BlogId)
        {
            _blogRepository.DeleteBlog(BlogId);
            TempData["message"] = $"{BlogId} numarali kayit silindi";
            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            if (_blogRepository.GetById(id) == null)
            {
                return NotFound();
            }
            
            return View(_blogRepository.GetById(id));
        }




        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            return View(new Blog());
         
        }

        [HttpPost]
        public IActionResult Create(Blog entity)
        {
            if (ModelState.IsValid)
            {
                _blogRepository.SaveBlog(entity);
                TempData["message"] = $"{entity.Title} kayit edildi";
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");

            return View(entity);
        }





        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");
            
            return View(_blogRepository.GetById((int) id));
             
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Blog entity, IFormFile file)
        {
           
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    entity.Image = file.FileName;
                    
                    _blogRepository.SaveBlog(entity);
                    TempData["message"] = $"{entity.Title} kayit edildi";
                    return RedirectToAction("List");    
                }
               
            }
                    _blogRepository.SaveBlog(entity);


            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "CategoryId", "Name");

            return RedirectToAction("List");
        }
    }
}

BlogApp/Controllers/CategoryController.cs
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryRepository repository;
        public CategoryController(ICategoryRepository _repo)
        {
            repository = _repo;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List()
        {
            return View(repository.GetAll());
        }
      
        [HttpGet]
        public IActionResult AddOrUpdate(int? id)
        {
            if (id == null)
            {
                return View(new Category());
            }
            else
            {
                return View(repository.GetById((int)id));
            }
            
        }
        [HttpPost]
        public IActionResult AddOrUpdate(Category entity)
        {
            if (ModelState.IsValid)
            {

                repository.SaveCategory(entity);
                TempData["message"] = $"{entity.Name} kayit edildi";
                return RedirectToAction("List");
            }
            return View(entity);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            repository.DeleteCategory(id);

            return RedirectToAction("List");
        }
    }
}

BlogApp/Controllers/HomeController.cs
using BlogApp.Data.Abstract;
using BlogApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.Controllers
{
    public class HomeController : Controller
    {
        private IBlogRepository blogRepository;
        public HomeController(IBlogRepository repository)
        {
            blogRepository = repository;
        }
        public IActionResult Index()
        {
            HomeBlogModel model = new HomeBlogModel();

            model.HomeBlogs = blogRepository.GetAll().Where(i => i.isApproved && i.isHome).ToList();
            model.SliderBlogs = blogRepository.GetAll().Where(i => i.isApproved && i.isSlider).ToList();

            return View(model);
        }
        public IActionResult Details()
        {
            return View();
        } 
        public IActionResult List()
        {
            return View();
;        }
    }
}

BlogApp/ViewComponents/CategoryMenuViewComponent.cs
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.ViewComponents
{
    public class CategoryMenuViewComponent: ViewComponent
    {
        private ICategoryRepository _repository;
        public CategoryMenuViewComponent(ICategoryRepository repo)
        {
            _repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(_repository.GetAll());
        }
    }
}

BlogApp/Views/Blog/AddOrUpdate.cshtml
@model Blog
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Create</h2>
    <br />

    <form asp-controller="Blog" asp-action="AddOrUpdate" method="post">
        <input type="hidden" asp-for="BlogId" />
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Body">Body</label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Image">Image</label>
            <input asp-for="Image" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories">
                <option disabled selected value="">Select Category</option>

            </select>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isApproved" class="form-check-input" />
                is approved
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isHome" class="form-check-input" />
                is Home
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isSlider" class="form-check-input" />
                is Slider
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div> 

BlogApp/Views/Blog/Create.cshtml
@model Blog
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <h2>Create</h2>
    <br />

    <form asp-controller="Blog" asp-action="Create" method="post">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control">
        </div>
         <div class="form-group">
            <label asp-for="Image">Image</label>
            <input asp-for="Image" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories">
                <option disabled selected value="">Select Category</option>

            </select>
        </div>
      

        <button type="submit" class="btn btn-primary">Save blog</button>
    </form>
</div> 

BlogApp/Views/Blog/Delete.cshtml
@model Blog
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>@Model.Title kaydi silmek istiyormusunu?</h2>

<form asp-controller="Blog" asp-action="Delete" method="post">
    <input type="hidden" asp-for="BlogId" />
    <button type="submit" class="btn btn-primary">Delete</button>
</form> 

BlogApp/Views/Blog/Details.cshtml
@model Blog
  

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu");

        </div>
        <div class="col-md-9">
            <div class="card mb-2">
                <div class="card-header">
                    @Model.Title
                </div>
                <img class="card-img-top" src="~/img/@Model.Image" alt="Card image cap">

                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Html.Raw(Model.Body)</p>
                </div>
            </div>
        </div>
    </div>
</div>

BlogApp/Views/Blog/Edit.cshtml
@model Blog
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section scripts{
    <script src="~/lib/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace("Body");
</script>
}
<div class="container">
    <h2>Edit blog</h2>
    <br />

    <form asp-controller="Blog" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="BlogId" />
        <input type="hidden" asp-for="Image" />
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Body">Body</label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <img src="~/img/@Model.Image" width="120" />
            <input type="file" name="file" id="file" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories">
                <option disabled selected value="">Select Category</option>

            </select>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isApproved" class="form-check-input" />
                is approved
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isHome" class="form-check-input" />
                is Home
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isSlider" class="form-check-input" />
                is Slider
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div> 

BlogApp/Views/Blog/Index.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "Home Page";
}
<div class="row mt-3">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">

        @Html.Partial("_BlogList", Model)

    </div>
</div>

BlogApp/Views/Blog/List.cshtml
@model IEnumerable<Blog>
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Blog List</h2>
    <hr />
    <div>
        <a class="btn btn-primary" href="/Blog/Create" >Create</a>
    </div>
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>is Approved</th>
                            <th>is Home</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.BlogId</td>
                            <td>
                                <img src="~/img/@item.Image" width="100" />
                            </td>
                            <td>@item.Title</td>

                            <td>@item.Date</td>
                            <td>
                                @if (@item.isApproved)
                                {


                                    <i class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                @if (@item.isHome)
                                {


                                    <i class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                @if (@item.isSlider)
                                {


                                    <i class="fa fa-check" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                }
                            </td>
                            <td>
                                <a class="btn btn-primary btn-sm" asp-controller="Blog" asp-action="Edit" asp-route-id="@item.BlogId">Edit</a>
                            </td>
                            <td>
                                <a class="btn btn-danger btn-sm" asp-controller="Blog" asp-action="Delete" asp-route-id="@item.BlogId">Delete</a>
                            </td>


                        </tr>

                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    Blog eklenmemis
                </div>
            }
        </div>
    </div>
</div>

BlogApp/Views/Category/AddOrUpdate.cshtml
@model Category
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Create</h2>
    <br />

    <form asp-controller="Category" asp-action="AddOrUpdate" method="post">
        <input type="hidden" asp-for="CategoryId" />
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div> 

BlogApp/Views/Category/List.cshtml
@model IEnumerable<BlogApp.Entity.Category>
@{ 
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Category List</h2>

    <div class="row">
        <hr />
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.CategoryId</td>
                                <td>@item.Name</td>
                                <td>
                                    <a class="btn btn-primary btn-sm" asp-controller="Category" asp-action="AddOrUpdate" asp-route-id="@item.CategoryId">Details</a>
                                </td>
                                <td>
                                    <a class="btn btn-danger btn-sm" asp-controller="Category" asp-action="Delete" asp-route-id="@item.CategoryId">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    Kategory eklenmemis
                </div>
            }
        </div>
    </div>
</div>

BlogApp/Views/Home/Details.cshtml
<div class="row mt-3">
    <div class="col-md-3">
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action active">
                Cras justo odio
            </a>
            <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
            <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
            <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
            <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
        </div>
    </div>
    <div class="col-md-9">

        <div class="card">
            <img class="card-img-top" src="./img/BlogImg.jpg" alt="Card image cap">
            <div class="card-header">
                Featured
            </div>
            <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>

    </div>
</div>

BlogApp/Views/Home/Index.cshtml
@model BlogApp.Models.HomeBlogModel
@{
    ViewData["Title"] = "Home Page";
}
<div class="row mt-3">
    <div class="col-md-3">
      @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        @Html.Partial("_Slider",Model.SliderBlogs)

        @Html.Partial("_BlogList", Model.HomeBlogs)

    </div>
</div>

BlogApp/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">
    @foreach (var item in Model)
    {
        <a 
           asp-controller="Blog" asp-action="Index" asp-route-id="@item.CategoryId"
           asp-route-id="@item.CategoryId"
           class="list-group-item list-group-item-action @(ViewBag.SelectedCategory==item.CategoryId.ToString()?"active": "")">

            @item.Name
        </a>
    }

   
</div>

BlogApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div id="main" class="container mt-3">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand" href="#">Admin</a>

                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">User page <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/blog/list">Blog <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/category/list">Category <span class="sr-only">(current)</span></a>
                    </li>

                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>



    </div>


    <div id="main" class="mt-3 container">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">
                @TempData["message"]
            </div>
        }
        @RenderBody()
    </div>

    @RenderSection("scripts", false)
</body>
</html>

BlogApp/Views/Shared/_BlogList.cshtml
@model IEnumerable<Blog>


@if (Model.Count() > 0)
{
    @foreach (var blog in Model)
    {
        <div class="card mb-2">
            <div class="card-header">
                @blog.Title
            </div>
            <img class="card-img-top" src="~/img/@blog.Image" alt="Card image cap">

            <div class="card-body">
                <h5 class="card-title">@blog.Title</h5>
                <p class="card-text">@blog.Description</p>
                <a asp-controller="Blog" asp-action="Details" asp-route-id="@blog.BlogId" class="btn btn-primary">Blog detils</a>
            </div>
        </div>
    }

}
else
{
    <h2>Blog eklenmemis</h2>
}

BlogApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <div id="main" class="container mt-3">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand" href="#">Blog</a>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/blog">Blog <span class="sr-only">(current)</span></a>
                    </li>

                </ul>
                @Html.Partial("_SearchBox")
            </div>
        </nav>


    
    </div>


    <div id="main" class="mt-3 container">
        @if (TempData["message"] != null) 
        {
            <div class="alert alert-success">
                @TempData["message"]
            </div>
        }
        @RenderBody()
    </div>
    @RenderSection("scripts", false)
</body>

</html>

BlogApp/Views/Shared/_SearchBox.cshtml
<form asp-controller="Blog" asp-action="Index" method="post" class="form-inline my-2 my-lg-0">
    <input id="q" name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

BlogApp/Views/Shared/_Slider.cshtml
@model IEnumerable<Blog>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        @for (int i = 0; i < Model.Count(); i++)
        {
            if (i == 0)
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="active"></li>

            }
            else
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="@i"></li>

            }
        }
    </ol>
    <div class="carousel-inner" role="listbox">
        @{ var index = 0;}
        @foreach (var item in Model)
        {
            if (index == 0)
            {
                <div class="carousel-item active">
                    <img class="d-block img-fluid" src="~/img/@item.Image" alt="@item.Title">
                    
                        <div class="carousel-caption d-none d-md-block">
                            <h5>@item.Title</h5>
                            <p>@item.Description</p>
                        </div>
                </div>
                index++;
            }
            else
            {
    <div class="carousel-item">
        <img class="d-block img-fluid" src="~/img/@item.Image" alt="@item.Title">

        <div class="carousel-caption d-none d-md-block">
            <h5>@item.Title</h5>
            <p>@item.Description</p>
        </div>
    </div>
            }

        }

    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>